version: '3'

services:
  web:
    container_name: apache
    image: httpd
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/
      #- ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf

  envoy:
    container_name: envoy
    image: envoyproxy/envoy:v1.27-latest
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "debug"]
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

