version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
    networks:
      - webnet

  envoy:
    image: envoyproxy/envoy:v1.27-latest
    container_name: envoy
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "debug"]
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy-certs:/etc/certs
    networks:
      - webnet

networks:
  webnet:
